data_entry:
  tasks:
    - api_link_discovery
    - api_link_content_extractor
  agents:
    - api_link_discovery
    - api_link_content_extractor
  process: sequential
  memory: False
  cache: False
  # The following are for test purposes
  verbose: True
  output_log_file: data_entry.json
