api_link_discovery:
  description: >
    Scrape {website_url} and create a sitemap of discovered links. Find all links in the sidebar/menu that lead to API endpoint usage Documentation. Focus on links from the sidebar or menu and avoid links in the main content section. Also avoid external links.
  expected_output: >
    A structured list of links containing page titles and url links.
  agent: >
    ApiLinkDiscoveryAgent
  # The following are for test purposes
  # markdown: True
  output_file: api_link_discovery_output.json

api_link_content_extractor:
  description: >
    Extract API endpoint usage information from the provided list of URLs - outputted from {website_urls}. Focus on structured data that includes endpoint paths, methods, parameters/headers (differentiating required and optional), expected outputs/return values and purpose.
  expected_output: >
    A structured list of API endpoint usage information including paths, methods, parameters, headers, expected outputs, and purpose.
  agent: >
    ApiLinkContentExtractorAgent
  context: >
    api_link_discovery
  # The following are for test purposes
  # markdown: True
  output_file: api_link_content_extractor_output.json